/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Zi7NNsdx2si
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/


import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { PriceChart } from "./PriceChart"
import { Strategy } from "~~/types/customTypes"

export function StrategyCard({ strategy }: { strategy: Strategy }) {
  return (
      // <Card className="w-full max-w-[1100px] grid grid-cols-[minmax(200px,1fr)_1fr] gap-0 p-6 bg-white rounded-xl">
      <Card className="w-full max-w-[1100px] grid grid-cols-[40%_60%] gap-4 p-6 bg-white rounded-xl">
        <div className="grid gap-4">
          <div className="flex items-center gap-4">
            <img src="/placeholder.svg" width={48} height={48} alt="Asset" className="rounded-md" /> {/*asset logo*/}
            <div className="flex flex-col">
              <h3 className="font-medium text-base">0.5 BTC</h3> {/*amount and asset*/}
               
              <Badge variant="outline" className="text-base" >
                $2,345
              </Badge>
            </div>
          </div>
          <div className="mt-4 flex flex-wrap gap-2">
            <Badge variant="outline" className="text-base" >
              Entry: $45,000
            </Badge>
            <Badge variant="outline" className="text-base" >
              Strategy: basic
            </Badge>
            <Badge variant="outline" className="text-base" >
              Duration: 30 days
            </Badge>
          </div>
        </div>
        <div className="h-4/5 pr-5 pt-5">
          <PriceChart priceData={strategy.priceData} />
        </div>
        <div className="col-span-2 flex justify-end gap-2">
          <Button variant="outline" className="text-base">Deposit</Button>
          <Button variant="outline" className="text-base">Withdraw</Button>
        </div>
      </Card>
  )
}
